//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoToolsMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UsersRCA = new HashSet<UsersRCA>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public short Active { get; set; }
        public Nullable<int> RoleLevel { get; set; }
    
        public virtual ICollection<UsersRCA> UsersRCA { get; set; }
    }
}
