//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoToolsMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    }
}
