//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoToolsMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRCA
    {
        public UsersRCA()
        {
            this.UsersRCA1 = new HashSet<UsersRCA>();
            this.UsersRCA11 = new HashSet<UsersRCA>();
            this.UsersRCA12 = new HashSet<UsersRCA>();
        }
    
        public string UsernameRCA { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DireccaoID { get; set; }
        public Nullable<int> PrestadorID { get; set; }
        public Nullable<int> PrestadorRCAID { get; set; }
        public Nullable<int> LinhaID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> LocalizacaoID { get; set; }
        public Nullable<int> Active { get; set; }
        public string Pass { get; set; }
        public string UserAlias { get; set; }
        public string Funcionario { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<int> FK_Group { get; set; }
        public string UsernameSFA { get; set; }
        public int FK_Role { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid FK_Status { get; set; }
        public System.DateTime StatusModifiedDate { get; set; }
        public bool CanSearch { get; set; }
        public Nullable<System.DateTime> InactivationDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool AllowMultipleLogins { get; set; }
        public string FK_ParentUser { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UsersRCA> UsersRCA1 { get; set; }
        public virtual UsersRCA UsersRCA2 { get; set; }
        public virtual ICollection<UsersRCA> UsersRCA11 { get; set; }
        public virtual UsersRCA UsersRCA3 { get; set; }
        public virtual ICollection<UsersRCA> UsersRCA12 { get; set; }
        public virtual UsersRCA UsersRCA4 { get; set; }
    }
}
